model_type: keyphrase
#tgt_type: one2one
tgt_type: no_sort

#data: data/keyphrase/kp20k/kp20k.one2one
data: data/keyphrase/kp20k/kp20k.one2many.small.meng17
save_model: models/kp20k/kp20k.one2one.transformer
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435

encoder_type: transformer
decoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 4

position_encoding: true

optim: adam
learning_rate: 2
param_init: 0
warmup_steps: 8000
decay_method: noam
label_smoothing: 0.1
adam_beta2: 0.998

batch_type: tokens
normalization: tokens
max_generator_batches: 2
accum_count: 4

#batch_size: 4096
batch_size: 1000
#batch_size: 24576
valid_batch_size: 20

train_steps: 200000
valid_steps: 10
report_every: 10

dropout: 0.2

share_embeddings: 'true'
copy_attn: 'true'
param_init_glorot: 'true'

log_file: output/kp20k/kp20k.one2one.transformer.log
log_file_level: DEBUG
exp: keyphrase-one2one-transformer-Layer4-Dim512-Emb512--Dropout0.2
tensorboard: 'true'
tensorboard_log_dir: runs/kp20k.one2one.transformer/

world_size: 1
gpu_ranks: []
master_port: 10000