model_type: keyphrase
tgt_type: verbatim_append

#train_from: models/keyphrase/meng17-one2seq/kp20k.one2seq.birnn.Dropout00_step_17000.pt
data: data/keyphrase/meng17/kp20k
# data: data/keyphrase/meng17/kp20k_small
#data: data/keyphrase/meng17/stackexchange
save_checkpoint_steps: 1000
keep_checkpoint: 10000
seed: 3435
train_steps: 100000
valid_steps: 16060 # no validation
report_every: 10


encoder_type: brnn
rnn_type: GRU_hyper
word_vec_size: 50
rnn_size: 80
layers: 1

optim: riemannian_adam
learning_rate: 8e-4
learning_rate_decay: 0.9
start_decay_steps: 20000
decay_steps: 5000
max_grad_norm: 2.0

#accum_count: 2
batch_size: 32
valid_batch_size: 32
dropout: 0.0

global_attention: hype_symm_bias

tensorboard: 'true'
log_file_level: DEBUG

copy_attn: 'true'
reuse_copy_attn: 'true'
coverage_attn: 'false'

context_gate: 'hyper'
input_feed: 1
share_embeddings: 'true'
bridge: 'true'

orth_reg: 'false'
lambda_orth_reg: 0.0
sem_cov: 'false'
lambda_sem_cov: 0.0

#tgt_enc: 'rnn'
#detach_tgt_enc: 'true'
#num_negsample: 31
use_ending_state: 'true'
exp: kp20k-one2seq-birnn-GRU150-EMB100-ATTNmlp-Dropout00
save_model: models/keyphrase/hyper-one2seq_symmatt_catseq/kp20k.one2seq.birnn.Dropout00
log_file: output/keyphrase/hyper-one2seq_symmatt_catseq/kp20k.one2seq.birnn.Dropout00.log
tensorboard_log_dir: runs/keyphrase/hyper-one2seq_symmatt_catseq/kp20k.one2seq.birnn.Dropout00/

world_size: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
#gpu_ranks: 0
#- 0
#- 1
master_port: 5000

wd: 0.0
poincare_type: 100D_cosh-dist-sq_init_trick
dataset: kp20k
network_type: hyperbolic
embedding_type: euclidiean
pretrained_wordembedding: 0
decision_type: hyp
